export const FETCH_ALL_BOOKINGS_PENDING = 'FETCH_ALL_BOOKINGS_PENDING';
export const FETCH_ALL_BOOKINGS_SUCCESS = 'FETCH_ALL_BOOKINGS_SUCCESS';
export const FETCH_ALL_BOOKINGS_FAILED = 'FETCH_ALL_BOOKINGS_FAILED';
export const CREATE_BOOKING_PENDING = 'CREATE_BOOKING_PENDING';
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS';
export const CREATE_BOOKING_FAILED = 'CREATE_BOOKING_FAILED';
